import 'package:moviehub/feature/genre/domain/entity/genre_entity.dart';
import 'package:moviehub/feature/movie/domain/entity/movie_entity.dart';

Future<void> demoDelay() => Future.delayed(Duration(seconds: 2));
final List<MovieEntity> movieData = [];
//  [
//   MovieEntity(
//     movieType: "Movie",
//     id: 1,
//     genreId: 101,
//     genre: 'Action',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=action1',
//     runtime: 130,
//     releaseDate: '2021-07-09',
//     averageRating: 4.3,
//     coverImage: 'https://images.unsplash.com/photo-1598899134739-24c46c2d3f34?auto=format&fit=crop&w=600&q=80',
//     title: 'Edge of Valor',
//     description: 'A daring mission to save the world from an impending threat.',
//     cast: [
//       CastModel(name: 'Chris Hamilton', type: 'Lead'),
//       CastModel(name: 'Emma Willis', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'john_doe', review: 'Thrilling from start to end.', rating: 4.5),
//       ReviewModel(user: 'jane_smith', review: 'Great action sequences.', rating: 4.0),
//     ],
//   ),
//   MovieEntity(
//     movieType: "Series",
//     id: 2,
//     genreId: 102,
//     genre: 'Drama',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=drama2',
//     runtime: 112,
//     releaseDate: '2020-03-15',
//     averageRating: 4.1,
//     coverImage: 'https://images.unsplash.com/photo-1605902711622-cfb43c4437b7?auto=format&fit=crop&w=600&q=80',
//     title: 'Tides of Time',
//     description: 'A heartfelt story of love, loss, and rediscovery.',
//     cast: [
//       CastModel(name: 'Laura Bennett', type: 'Lead'),
//       CastModel(name: 'Tom Clarkson', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'michael_lee', review: 'Emotional and beautifully acted.', rating: 4.2),
//     ],
//   ),
//   MovieEntity(
//     movieType: "Movie",
//     id: 3,
//     genreId: 103,
//     genre: 'Sci-Fi',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=scifi3',
//     runtime: 145,
//     releaseDate: '2019-12-20',
//     averageRating: 4.5,
//     coverImage: 'https://images.unsplash.com/photo-1581090700227-1e37b190418e?auto=format&fit=crop&w=600&q=80',
//     title: 'Galactic Frontier',
//     description: 'An interstellar journey through unknown galaxies.',
//     cast: [
//       CastModel(name: 'Nathan Cross', type: 'Lead'),
//       CastModel(name: 'Isabelle Greene', type: 'Supporting'),
//       CastModel(name: 'Liam Torres', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'astrofan', review: 'Visually stunning space opera.', rating: 4.7),
//     ],
//   ),
//   MovieEntity(
//     movieType: "Movie",
//     id: 4,
//     genreId: 104,
//     genre: 'Horror',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=horror4',
//     runtime: 98,
//     releaseDate: '2022-10-31',
//     averageRating: 3.9,
//     coverImage: 'https://images.unsplash.com/photo-1603984286082-98d0d37e1a22?auto=format&fit=crop&w=600&q=80',
//     title: 'Whispers in the Dark',
//     description: 'A small town is haunted by mysterious whispers.',
//     cast: [
//       CastModel(name: 'Sophie Lin', type: 'Lead'),
//       CastModel(name: 'Ethan Blake', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'horror_buff', review: 'Creepy and atmospheric.', rating: 4.0),
//     ],
//   ),
//   MovieEntity(
//     movieType: "Movie",
//     id: 5,
//     genreId: 105,
//     genre: 'Comedy',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=comedy5',
//     runtime: 105,
//     releaseDate: '2021-05-21',
//     averageRating: 4.0,
//     coverImage: 'https://images.unsplash.com/photo-1533236897111-3e94666b2edf?auto=format&fit=crop&w=600&q=80',
//     title: 'The Misfits Club',
//     description: 'An unlikely group forms a hilarious bond over shared misadventures.',
//     cast: [
//       CastModel(name: 'Jake Rivers', type: 'Lead'),
//       CastModel(name: 'Lily Grant', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'comedylover', review: 'I laughed so much!', rating: 4.3),
//       ReviewModel(user: 'puzzlefan', review: 'Smart and gripping.', rating: 4.5),
//       ReviewModel(user: 'fantasyfan', review: 'Magical and epic.', rating: 4.6),
//       ReviewModel(user: 'comedylover', review: 'I laughed so much!', rating: 4.3),
//       ReviewModel(user: 'puzzlefan', review: 'Smart and gripping.', rating: 4.5),
//       ReviewModel(user: 'fantasyfan', review: 'Magical and epic.', rating: 4.6),
//     ],
//   ),
//   MovieEntity(
//     id: 6,
//     movieType: "Series",
//     genreId: 106,
//     genre: 'Thriller',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=thriller6',
//     runtime: 120,
//     releaseDate: '2018-09-14',
//     averageRating: 4.2,
//     coverImage: 'https://images.unsplash.com/photo-1590080876035-8a2ea18a662e?auto=format&fit=crop&w=600&q=80',
//     title: 'The Last Cipher',
//     description: 'A cryptologist races against time to crack an unsolvable code.',
//     cast: [
//       CastModel(name: 'Victor Cole', type: 'Lead'),
//       CastModel(name: 'Maya Dawson', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'puzzlefan', review: 'Smart and gripping.', rating: 4.5),
//     ],
//   ),
//   MovieEntity(
//     id: 7,
//     genreId: 107,
//     movieType: "Movie",
//     genre: 'Fantasy',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=fantasy7',
//     runtime: 137,
//     releaseDate: '2017-06-11',
//     averageRating: 4.4,
//     coverImage: 'https://images.unsplash.com/photo-1531306728370-e2ebd9fd46f9?auto=format&fit=crop&w=600&q=80',
//     title: 'The Enchanted Realm',
//     description: 'A young hero embarks on a quest to save a mystical land.',
//     cast: [
//       CastModel(name: 'Ella Carter', type: 'Lead'),
//       CastModel(name: 'Oscar Reed', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'fantasyfan', review: 'Magical and epic.', rating: 4.6),
//     ],
//   ),
//   MovieEntity(
//     id: 8,
//     movieType: "Movie",
//     genreId: 108,
//     genre: 'Biography',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=bio8',
//     runtime: 150,
//     releaseDate: '2020-01-24',
//     averageRating: 4.3,
//     coverImage: 'https://images.unsplash.com/photo-1525943839993-1efb4f9c63d6?auto=format&fit=crop&w=600&q=80',
//     title: 'Legacy of a Dreamer',
//     description: 'The inspiring life of a groundbreaking innovator.',
//     cast: [
//       CastModel(name: 'Samuel Ford', type: 'Lead'),
//       CastModel(name: 'Clara Monroe', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'historybuff', review: 'Inspirational and moving.', rating: 4.4),
//     ],
//   ),
//   MovieEntity(
//     id: 9,
//     movieType: "Series",
//     genreId: 109,
//     genre: 'Adventure',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=adventure9',
//     runtime: 140,
//     releaseDate: '2016-07-19',
//     averageRating: 4.1,
//     coverImage: 'https://images.unsplash.com/photo-1516478177764-9fe5bd7e971b?auto=format&fit=crop&w=600&q=80',
//     title: 'Lost in the Wild',
//     description: 'An expedition goes awry deep in the Amazon rainforest.',
//     cast: [
//       CastModel(name: 'Liam Parker', type: 'Lead'),
//       CastModel(name: 'Nina Collins', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'adventurefan', review: 'A thrilling journey.', rating: 4.1),
//     ],
//   ),
//   MovieEntity(
//     movieType: "Serie",
//     id: 10,
//     genreId: 110,
//     genre: 'Romance',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=romance10',
//     runtime: 115,
//     releaseDate: '2019-02-14',
//     averageRating: 3.8,
//     coverImage: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?auto=format&fit=crop&w=600&q=80',
//     title: 'Hearts Entwined',
//     description: 'Two souls cross paths in the city of love.',
//     cast: [
//       CastModel(name: 'Isla Thompson', type: 'Lead'),
//       CastModel(name: 'Ryan Evans', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'romantic88', review: 'Sweet and charming.', rating: 3.9),
//     ],
//   ),
//   MovieEntity(
//     id: 11,
//     movieType: "Movie",
//     genreId: 111,
//     genre: 'Animation',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=animation11',
//     runtime: 95,
//     releaseDate: '2018-11-22',
//     averageRating: 4.6,
//     coverImage: 'https://images.unsplash.com/photo-1524386326396-3b2d00833085?auto=format&fit=crop&w=600&q=80',
//     title: 'Skybound Adventures',
//     description: 'Animated tale of friendship and discovery in the skies.',
//     cast: [
//       CastModel(name: 'Voice of Ava Summers', type: 'Voice'),
//       CastModel(name: 'Voice of Ben Ryder', type: 'Voice'),
//     ],
//     ratings: [
//       ReviewModel(user: 'animationfan', review: 'Beautiful visuals and heartwarming.', rating: 4.7),
//     ],
//   ),
//   MovieEntity(
//     id: 12,
//     genreId: 112,
//     movieType: "Movie",
//     genre: 'Mystery',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=mystery12',
//     runtime: 128,
//     releaseDate: '2017-04-18',
//     averageRating: 4.0,
//     coverImage: 'https://images.unsplash.com/photo-1505843296828-27c362dfd27b?auto=format&fit=crop&w=600&q=80',
//     title: 'Shadows of Deceit',
//     description: 'A detective uncovers shocking secrets behind a cold case.',
//     cast: [
//       CastModel(name: 'Daniel West', type: 'Lead'),
//       CastModel(name: 'Grace Patel', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'mysteryfan', review: 'Keeps you guessing till the end.', rating: 4.2),
//     ],
//   ),
//   MovieEntity(
//     id: 13,
//     genreId: 113,
//     movieType: "Movie",
//     genre: 'Musical',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=musical13',
//     runtime: 110,
//     releaseDate: '2021-12-25',
//     averageRating: 4.1,
//     coverImage: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=600&q=80',
//     title: 'Melody of Dreams',
//     description: 'An aspiring musician’s journey to stardom.',
//     cast: [
//       CastModel(name: 'Jasmine Rivera', type: 'Lead'),
//       CastModel(name: 'Leo Brooks', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'musiclover', review: 'Wonderful soundtrack!', rating: 4.3),
//     ],
//   ),
//   MovieEntity(
//     id: 14,
//     movieType: "Movie",
//     genreId: 114,
//     genre: 'Documentary',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=documentary14',
//     runtime: 90,
//     releaseDate: '2022-04-10',
//     averageRating: 4.5,
//     coverImage: 'https://images.unsplash.com/photo-1607697988502-3f93c81c5ad6?auto=format&fit=crop&w=600&q=80',
//     title: 'Earth Unseen',
//     description: 'A deep dive into Earth’s most remote ecosystems.',
//     cast: [],
//     ratings: [
//       ReviewModel(user: 'naturefan', review: 'Eye-opening and informative.', rating: 4.6),
//     ],
//   ),
//   MovieEntity(
//     id: 15,
//     genreId: 115,
//     movieType: "Series",
//     genre: 'Crime',
//     movieLink: null,
//     trailerLink: 'https://youtube.com/watch?v=crime15',
//     runtime: 122,
//     releaseDate: '2015-08-28',
//     averageRating: 4.0,
//     coverImage: 'https://images.unsplash.com/photo-1581091870624-81ab7c8700d5?auto=format&fit=crop&w=600&q=80',
//     title: 'Underworld Ties',
//     description: 'A gritty tale of crime and betrayal in the city underbelly.',
//     cast: [
//       CastModel(name: 'Marcus Hall', type: 'Lead'),
//       CastModel(name: 'Sara Cruz', type: 'Supporting'),
//     ],
//     ratings: [
//       ReviewModel(user: 'crimefan', review: 'Gritty and intense.', rating: 4.1),
//     ],
//   ),
// ];
final List<GenreEntity> genreList = [];
// [
//   GenreEntity(
//     id: 1,
//     name: 'Action',
//     image: 'https://images.unsplash.com/photo-1601933471669-1a4e02f7f84d?w=800',
//   ),
//   GenreEntity(
//     id: 2,
//     name: 'Comedy',
//     image: 'https://images.unsplash.com/photo-1598899134739-87abdc6eb8b0?w=800',
//   ),
//   GenreEntity(
//     id: 3,
//     name: 'Drama',
//     image: 'https://images.unsplash.com/photo-1517602302552-471fe67acf66?w=800',
//   ),
//   GenreEntity(
//     id: 4,
//     name: 'Horror',
//     image: 'https://images.unsplash.com/photo-1601758125946-9b2b3a6c0fa0?w=800',
//   ),
//   GenreEntity(
//     id: 5,
//     name: 'Sci-Fi',
//     image: 'https://images.unsplash.com/photo-1549921296-3a20f61a6b74?w=800',
//   ),
// ];
